Traceback (most recent call last):
  File "/mnt/d/JetBrains/PyCharm 2022.2.3/plugins/python/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/mnt/d/JetBrains/PyCharm 2022.2.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/rafa/fs_learning/main.py", line 252, in <module>
    main(args)
  File "/home/rafa/fs_learning/main.py", line 52, in main
    data_loader_train, data_loader_val = get_loaders(args, num_tasks, global_rank)
  File "/home/rafa/fs_learning/datasets/__init__.py", line 75, in get_loaders
    dataset_train, dataset_vals, _ = get_sets(args)
  File "/home/rafa/fs_learning/datasets/__init__.py", line 27, in get_sets
    trainSet = FullMetaDatasetH5(args, Split.TRAIN)
  File "/home/rafa/fs_learning/datasets/meta_h5_dataset.py", line 54, in __init__
    dataset_spec = dataset_spec_lib.load_dataset_spec(dataset_records_path)
  File "/home/rafa/fs_learning/datasets/meta_dataset/dataset_spec.py", line 906, in load_dataset_spec
    raise RuntimeError('No dataset_spec file found in directory %s' % dataset_records_path)
RuntimeError: No dataset_spec file found in directory meta_dataset_h5/aircraft
Not using distributed mode
